### ISSUE TITLE
Fungsi %>% ?

### ISSUE THREAD

**Issue by hendro93** [advanced-statistics/3_discriminant-analysis#1]
Fungsi %>% itu untuk apa ya Pak?

(Hendra Kusumah)

**Comment by apriandito** [comment]
Fungsi %>% merupakan operator pipe yang bertujuan untuk membuat fungsi berantai. Jadi kita bisa melakukan pengolahan terhadap data secara berturut-turut. Pak Hendro bisa melihat ini untuk lebih jelasnya. https://www.datacamp.com/community/tutorials/pipe-r-tutorial

**Comment by hendro93** [comment]
Terimakasih Pak Dito!
